//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortafolioEntities : DbContext
    {
        public PortafolioEntities()
            : base("name=PortafolioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Etiqueta> Etiqueta { get; set; }
        public virtual DbSet<MaestroEtiquetaPorta> MaestroEtiquetaPorta { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Portafolio> Portafolio { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
    }
}
