//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroEtiquetaPorta
    {
        public int IDMaestroEtiquetaPorta { get; set; }
        public Nullable<int> IDPortafolio { get; set; }
        public Nullable<int> IDEtiqueta { get; set; }
    
        public virtual Etiqueta Etiqueta { get; set; }
        public virtual Portafolio Portafolio { get; set; }
    }
}
