//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public int IDPerfil { get; set; }
        public string Titular { get; set; }
        public string Extracto { get; set; }
        public string ImgTitular { get; set; }
        public string ImgExtracto { get; set; }
    }
}
