//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public int IDSkill { get; set; }
        public string skill1 { get; set; }
        public Nullable<int> porcentaje { get; set; }
    }
}
